FROM golang:latest AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gophermart cmd/gophermart/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=build /app/gophermart .
COPY --from=build /app/migrations ./migrations
CMD ["./gophermart"]
