version: '3'

services:
  gofermart:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
    environment:
      RUN_ADDRESS: ":${APP_PORT}"
      ACCRUAL_SYSTEM_ADDRESS: ""
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      DATABASE_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"  # Reusing POSTGRES_HOST environment variable here
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    hostname: "${POSTGRES_HOST}"  # Reusing the same environment variable for the PostgreSQL service hostname

volumes:
  postgres_data:
